[
    {
        "url": "https://api.github.com/repos/conda/conda-build/issues/comments/280838655",
        "html_url": "https://github.com/conda/conda-build/issues/1711#issuecomment-280838655",
        "issue_url": "https://api.github.com/repos/conda/conda-build/issues/1711",
        "id": 280838655,
        "node_id": "MDEyOklzc3VlQ29tbWVudDI4MDgzODY1NQ==",
        "user": {
            "login": "ghost",
            "id": 10137,
            "node_id": "MDQ6VXNlcjEwMTM3",
            "avatar_url": "https://avatars3.githubusercontent.com/u/10137?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/ghost",
            "html_url": "https://github.com/ghost",
            "followers_url": "https://api.github.com/users/ghost/followers",
            "following_url": "https://api.github.com/users/ghost/following{/other_user}",
            "gists_url": "https://api.github.com/users/ghost/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/ghost/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/ghost/subscriptions",
            "organizations_url": "https://api.github.com/users/ghost/orgs",
            "repos_url": "https://api.github.com/users/ghost/repos",
            "events_url": "https://api.github.com/users/ghost/events{/privacy}",
            "received_events_url": "https://api.github.com/users/ghost/received_events",
            "type": "User",
            "site_admin": false
        },
        "created_at": "2017-02-18T11:07:13Z",
        "updated_at": "2017-02-18T11:07:13Z",
        "author_association": "NONE",
        "body": "Thanks,.. I'll try that.. I need it on ubuntu.. I'll figure it out and release a package.."
    },
    {
        "url": "https://api.github.com/repos/conda/conda-build/issues/comments/50175146",
        "html_url": "https://github.com/conda/conda-build/issues/131#issuecomment-50175146",
        "issue_url": "https://api.github.com/repos/conda/conda-build/issues/131",
        "id": 50175146,
        "node_id": "MDEyOklzc3VlQ29tbWVudDUwMTc1MTQ2",
        "user": {
            "login": "scw",
            "id": 1314,
            "node_id": "MDQ6VXNlcjEzMTQ=",
            "avatar_url": "https://avatars3.githubusercontent.com/u/1314?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/scw",
            "html_url": "https://github.com/scw",
            "followers_url": "https://api.github.com/users/scw/followers",
            "following_url": "https://api.github.com/users/scw/following{/other_user}",
            "gists_url": "https://api.github.com/users/scw/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/scw/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/scw/subscriptions",
            "organizations_url": "https://api.github.com/users/scw/orgs",
            "repos_url": "https://api.github.com/users/scw/repos",
            "events_url": "https://api.github.com/users/scw/events{/privacy}",
            "received_events_url": "https://api.github.com/users/scw/received_events",
            "type": "User",
            "site_admin": false
        },
        "created_at": "2014-07-25T16:50:43Z",
        "updated_at": "2014-07-25T16:50:43Z",
        "author_association": "CONTRIBUTOR",
        "body": "Also seeing this here. Just commenting out the offending `assert` let the build go on its way without issue. [The commit](https://github.com/conda/conda-build/commit/fe7f773010f4c8c200298c83a4164ca404626d52) which added the `is_obj` test, for context.\n"
    },
    {
        "url": "https://api.github.com/repos/conda/conda-build/issues/comments/146595827",
        "html_url": "https://github.com/conda/conda-build/pull/615#issuecomment-146595827",
        "issue_url": "https://api.github.com/repos/conda/conda-build/issues/615",
        "id": 146595827,
        "node_id": "MDEyOklzc3VlQ29tbWVudDE0NjU5NTgyNw==",
        "user": {
            "login": "scw",
            "id": 1314,
            "node_id": "MDQ6VXNlcjEzMTQ=",
            "avatar_url": "https://avatars3.githubusercontent.com/u/1314?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/scw",
            "html_url": "https://github.com/scw",
            "followers_url": "https://api.github.com/users/scw/followers",
            "following_url": "https://api.github.com/users/scw/following{/other_user}",
            "gists_url": "https://api.github.com/users/scw/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/scw/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/scw/subscriptions",
            "organizations_url": "https://api.github.com/users/scw/orgs",
            "repos_url": "https://api.github.com/users/scw/repos",
            "events_url": "https://api.github.com/users/scw/events{/privacy}",
            "received_events_url": "https://api.github.com/users/scw/received_events",
            "type": "User",
            "site_admin": false
        },
        "created_at": "2015-10-08T16:12:05Z",
        "updated_at": "2015-10-08T16:12:20Z",
        "author_association": "CONTRIBUTOR",
        "body": "For most English grammar, negation follows the [auxillary or special verb](https://en.wikipedia.org/wiki/English_grammar#Negation) used to connect the action. It's fine to keep, just thought it improved readability this way.\n"
    },
    {
        "url": "https://api.github.com/repos/conda/conda-build/issues/comments/324518138",
        "html_url": "https://github.com/conda/conda-build/issues/2307#issuecomment-324518138",
        "issue_url": "https://api.github.com/repos/conda/conda-build/issues/2307",
        "id": 324518138,
        "node_id": "MDEyOklzc3VlQ29tbWVudDMyNDUxODEzOA==",
        "user": {
            "login": "scw",
            "id": 1314,
            "node_id": "MDQ6VXNlcjEzMTQ=",
            "avatar_url": "https://avatars3.githubusercontent.com/u/1314?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/scw",
            "html_url": "https://github.com/scw",
            "followers_url": "https://api.github.com/users/scw/followers",
            "following_url": "https://api.github.com/users/scw/following{/other_user}",
            "gists_url": "https://api.github.com/users/scw/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/scw/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/scw/subscriptions",
            "organizations_url": "https://api.github.com/users/scw/orgs",
            "repos_url": "https://api.github.com/users/scw/repos",
            "events_url": "https://api.github.com/users/scw/events{/privacy}",
            "received_events_url": "https://api.github.com/users/scw/received_events",
            "type": "User",
            "site_admin": false
        },
        "created_at": "2017-08-24T02:50:51Z",
        "updated_at": "2017-08-24T02:58:10Z",
        "author_association": "CONTRIBUTOR",
        "body": "Hi @msarahan thanks for the reply. I neglected to include enough details: I'm rebuilding a package on Windows that I've previously build successfully, currently using:\r\n```\r\nconda                     4.3.24                   py35_0\r\nconda-build               3.0.10           py35h689962e_0\r\n```\r\nMy environment also included the `patch` package, version 2.5.9. When I tried to rebuild the same package I'd built previously, I received the error above. Here's what I see in the defaults channel for the package:\r\n\r\n```\r\npatch                        1.12.11                  py27_0  defaults\r\n                             2.5                           0  defaults\r\n                             2.5.9                         0  defaults\r\n                          *  2.5.9                         1  defaults\r\n```\r\n\r\nI've created a simple repository containing a stripped down version of package that previously I was able to build:\r\n\r\n  https://github.com/scw/netcdf-patch-example/\r\n\r\nThat should hopefully include enough details to reproduce the behavior. On my machine, that will consistently cause a crash in the patching phase, though conda-build still will try to continue after the failed patching. I've also updated the title, because the patch in question has LF line endings already. In the absence of an updated `patch` on anaconda.org which doesn't exhibit this behavior, I think for Windows, it makes sense to have `m2-patch` be 'the right way' to apply patches. On MacOS and Linux, it's either available out of the box or one apt-get away, but on Windows that's not the case. I was suggesting `m2-patch` as a dependency on Windows because it would simplify the workflow somewhat. If there are specific details of my environment which are causing this and it's not reproducible, this issue can be closed.\r\n\r\nPerhaps a separate issue is that the documentation doesn't really communicate how to generate patches that conda-build can consume at the moment, I can open a separate documentation issue on that, and provide some suggested copy if that'd be useful. I've just been using `diff -u` and `git diff` to generate my patches, but I see that there are some more sophisticated options using e.g. `git format-patch` which may be worth documenting.\r\n\r\nThanks for all your great work on Conda!\r\n"
    },
    {
        "url": "https://api.github.com/repos/conda/conda-build/issues/comments/324775760",
        "html_url": "https://github.com/conda/conda-build/issues/2307#issuecomment-324775760",
        "issue_url": "https://api.github.com/repos/conda/conda-build/issues/2307",
        "id": 324775760,
        "node_id": "MDEyOklzc3VlQ29tbWVudDMyNDc3NTc2MA==",
        "user": {
            "login": "scw",
            "id": 1314,
            "node_id": "MDQ6VXNlcjEzMTQ=",
            "avatar_url": "https://avatars3.githubusercontent.com/u/1314?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/scw",
            "html_url": "https://github.com/scw",
            "followers_url": "https://api.github.com/users/scw/followers",
            "following_url": "https://api.github.com/users/scw/following{/other_user}",
            "gists_url": "https://api.github.com/users/scw/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/scw/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/scw/subscriptions",
            "organizations_url": "https://api.github.com/users/scw/orgs",
            "repos_url": "https://api.github.com/users/scw/repos",
            "events_url": "https://api.github.com/users/scw/events{/privacy}",
            "received_events_url": "https://api.github.com/users/scw/received_events",
            "type": "User",
            "site_admin": false
        },
        "created_at": "2017-08-24T22:35:40Z",
        "updated_at": "2017-08-24T23:45:12Z",
        "author_association": "CONTRIBUTOR",
        "body": "Right, as it does for @ratstache it causes a full windows crash. The rest of conda build will  continue, without the patch being applied, but eventually hangs, requiring the process be killed. Here's the output of dos2unix on this patch file:\r\n```\r\n$ dos2unix -i hdf5.patch\r\n       0      33       0  no_bom    text    hdf5.patch\r\n```\r\nSo 33 LF (Unix) line breaks only. None of the files in the above repository have Windows-style line endings. I can confirm that this package builds for me on 2.1.17, but not on any of the 3.x versions I've tested."
    },
    {
        "url": "https://api.github.com/repos/conda/conda-build/issues/comments/329215419",
        "html_url": "https://github.com/conda/conda-build/issues/2307#issuecomment-329215419",
        "issue_url": "https://api.github.com/repos/conda/conda-build/issues/2307",
        "id": 329215419,
        "node_id": "MDEyOklzc3VlQ29tbWVudDMyOTIxNTQxOQ==",
        "user": {
            "login": "scw",
            "id": 1314,
            "node_id": "MDQ6VXNlcjEzMTQ=",
            "avatar_url": "https://avatars3.githubusercontent.com/u/1314?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/scw",
            "html_url": "https://github.com/scw",
            "followers_url": "https://api.github.com/users/scw/followers",
            "following_url": "https://api.github.com/users/scw/following{/other_user}",
            "gists_url": "https://api.github.com/users/scw/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/scw/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/scw/subscriptions",
            "organizations_url": "https://api.github.com/users/scw/orgs",
            "repos_url": "https://api.github.com/users/scw/repos",
            "events_url": "https://api.github.com/users/scw/events{/privacy}",
            "received_events_url": "https://api.github.com/users/scw/received_events",
            "type": "User",
            "site_admin": false
        },
        "created_at": "2017-09-13T16:02:19Z",
        "updated_at": "2017-09-13T16:02:19Z",
        "author_association": "CONTRIBUTOR",
        "body": "@mingwandroid Yes, `m2-patch` is definitely the right answer. However, other users will still hit this if they happen to have `patch` which will still be used by `conda-build`. I recommend making `m2-patch` a requirement of conda-build when running on Windows."
    },
    {
        "url": "https://api.github.com/repos/conda/conda-build/issues/comments/433121673",
        "html_url": "https://github.com/conda/conda-build/issues/3205#issuecomment-433121673",
        "issue_url": "https://api.github.com/repos/conda/conda-build/issues/3205",
        "id": 433121673,
        "node_id": "MDEyOklzc3VlQ29tbWVudDQzMzEyMTY3Mw==",
        "user": {
            "login": "scw",
            "id": 1314,
            "node_id": "MDQ6VXNlcjEzMTQ=",
            "avatar_url": "https://avatars3.githubusercontent.com/u/1314?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/scw",
            "html_url": "https://github.com/scw",
            "followers_url": "https://api.github.com/users/scw/followers",
            "following_url": "https://api.github.com/users/scw/following{/other_user}",
            "gists_url": "https://api.github.com/users/scw/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/scw/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/scw/subscriptions",
            "organizations_url": "https://api.github.com/users/scw/orgs",
            "repos_url": "https://api.github.com/users/scw/repos",
            "events_url": "https://api.github.com/users/scw/events{/privacy}",
            "received_events_url": "https://api.github.com/users/scw/received_events",
            "type": "User",
            "site_admin": false
        },
        "created_at": "2018-10-25T16:38:26Z",
        "updated_at": "2018-10-25T16:40:37Z",
        "author_association": "CONTRIBUTOR",
        "body": "I also hit this issue in a pipeline, and confirm `conda update --all` works. For many use cases, this should be resolved when the newer versions are bundled within the Miniconda installer and docker image."
    },
    {
        "url": "https://api.github.com/repos/conda/conda-build/issues/comments/211658611",
        "html_url": "https://github.com/conda/conda-build/pull/8#issuecomment-211658611",
        "issue_url": "https://api.github.com/repos/conda/conda-build/issues/8",
        "id": 211658611,
        "node_id": "MDEyOklzc3VlQ29tbWVudDIxMTY1ODYxMQ==",
        "user": {
            "login": "brentp",
            "id": 1739,
            "node_id": "MDQ6VXNlcjE3Mzk=",
            "avatar_url": "https://avatars2.githubusercontent.com/u/1739?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/brentp",
            "html_url": "https://github.com/brentp",
            "followers_url": "https://api.github.com/users/brentp/followers",
            "following_url": "https://api.github.com/users/brentp/following{/other_user}",
            "gists_url": "https://api.github.com/users/brentp/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/brentp/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/brentp/subscriptions",
            "organizations_url": "https://api.github.com/users/brentp/orgs",
            "repos_url": "https://api.github.com/users/brentp/repos",
            "events_url": "https://api.github.com/users/brentp/events{/privacy}",
            "received_events_url": "https://api.github.com/users/brentp/received_events",
            "type": "User",
            "site_admin": false
        },
        "created_at": "2016-04-19T00:50:58Z",
        "updated_at": "2016-04-19T00:50:58Z",
        "author_association": "CONTRIBUTOR",
        "body": "is this documented somewhere? [this](http://conda.pydata.org/docs/building/environment-vars.html?highlight=template) is the most I could find.\n\ne.g. is it possible to define a custom template to inherit from?\n"
    },
    {
        "url": "https://api.github.com/repos/conda/conda-build/issues/comments/190936704",
        "html_url": "https://github.com/conda/conda-build/pull/800#issuecomment-190936704",
        "issue_url": "https://api.github.com/repos/conda/conda-build/issues/800",
        "id": 190936704,
        "node_id": "MDEyOklzc3VlQ29tbWVudDE5MDkzNjcwNA==",
        "user": {
            "login": "brentp",
            "id": 1739,
            "node_id": "MDQ6VXNlcjE3Mzk=",
            "avatar_url": "https://avatars2.githubusercontent.com/u/1739?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/brentp",
            "html_url": "https://github.com/brentp",
            "followers_url": "https://api.github.com/users/brentp/followers",
            "following_url": "https://api.github.com/users/brentp/following{/other_user}",
            "gists_url": "https://api.github.com/users/brentp/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/brentp/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/brentp/subscriptions",
            "organizations_url": "https://api.github.com/users/brentp/orgs",
            "repos_url": "https://api.github.com/users/brentp/repos",
            "events_url": "https://api.github.com/users/brentp/events{/privacy}",
            "received_events_url": "https://api.github.com/users/brentp/received_events",
            "type": "User",
            "site_admin": false
        },
        "created_at": "2016-03-01T22:31:56Z",
        "updated_at": "2016-03-01T22:31:56Z",
        "author_association": "CONTRIBUTOR",
        "body": "I realized it was incomplete. But the solution involves creating _another_ copy of a large data file. Is there a way to tell conda not to perform this check at all? --I mean is there a way to tell conda that it's just a static data file and doesn't need to be modified?\n"
    },
    {
        "url": "https://api.github.com/repos/conda/conda-build/issues/comments/206510367",
        "html_url": "https://github.com/conda/conda-build/pull/866#issuecomment-206510367",
        "issue_url": "https://api.github.com/repos/conda/conda-build/issues/866",
        "id": 206510367,
        "node_id": "MDEyOklzc3VlQ29tbWVudDIwNjUxMDM2Nw==",
        "user": {
            "login": "brentp",
            "id": 1739,
            "node_id": "MDQ6VXNlcjE3Mzk=",
            "avatar_url": "https://avatars2.githubusercontent.com/u/1739?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/brentp",
            "html_url": "https://github.com/brentp",
            "followers_url": "https://api.github.com/users/brentp/followers",
            "following_url": "https://api.github.com/users/brentp/following{/other_user}",
            "gists_url": "https://api.github.com/users/brentp/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/brentp/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/brentp/subscriptions",
            "organizations_url": "https://api.github.com/users/brentp/orgs",
            "repos_url": "https://api.github.com/users/brentp/repos",
            "events_url": "https://api.github.com/users/brentp/events{/privacy}",
            "received_events_url": "https://api.github.com/users/brentp/received_events",
            "type": "User",
            "site_admin": false
        },
        "created_at": "2016-04-06T18:47:13Z",
        "updated_at": "2016-04-06T18:47:13Z",
        "author_association": "CONTRIBUTOR",
        "body": "got it working on python3. I did a couple of force-pushes so I wouldn't have 10 commits fixing the issues. Looks like appveyor is failing for other reasons. \n"
    },
    {
        "url": "https://api.github.com/repos/conda/conda-build/issues/comments/206514592",
        "html_url": "https://github.com/conda/conda-build/pull/866#issuecomment-206514592",
        "issue_url": "https://api.github.com/repos/conda/conda-build/issues/866",
        "id": 206514592,
        "node_id": "MDEyOklzc3VlQ29tbWVudDIwNjUxNDU5Mg==",
        "user": {
            "login": "brentp",
            "id": 1739,
            "node_id": "MDQ6VXNlcjE3Mzk=",
            "avatar_url": "https://avatars2.githubusercontent.com/u/1739?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/brentp",
            "html_url": "https://github.com/brentp",
            "followers_url": "https://api.github.com/users/brentp/followers",
            "following_url": "https://api.github.com/users/brentp/following{/other_user}",
            "gists_url": "https://api.github.com/users/brentp/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/brentp/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/brentp/subscriptions",
            "organizations_url": "https://api.github.com/users/brentp/orgs",
            "repos_url": "https://api.github.com/users/brentp/repos",
            "events_url": "https://api.github.com/users/brentp/events{/privacy}",
            "received_events_url": "https://api.github.com/users/brentp/received_events",
            "type": "User",
            "site_admin": false
        },
        "created_at": "2016-04-06T19:01:28Z",
        "updated_at": "2016-04-06T19:01:28Z",
        "author_association": "CONTRIBUTOR",
        "body": "cheers!\n"
    },
    {
        "url": "https://api.github.com/repos/conda/conda-build/issues/comments/278214306",
        "html_url": "https://github.com/conda/conda-build/pull/866#issuecomment-278214306",
        "issue_url": "https://api.github.com/repos/conda/conda-build/issues/866",
        "id": 278214306,
        "node_id": "MDEyOklzc3VlQ29tbWVudDI3ODIxNDMwNg==",
        "user": {
            "login": "brentp",
            "id": 1739,
            "node_id": "MDQ6VXNlcjE3Mzk=",
            "avatar_url": "https://avatars2.githubusercontent.com/u/1739?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/brentp",
            "html_url": "https://github.com/brentp",
            "followers_url": "https://api.github.com/users/brentp/followers",
            "following_url": "https://api.github.com/users/brentp/following{/other_user}",
            "gists_url": "https://api.github.com/users/brentp/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/brentp/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/brentp/subscriptions",
            "organizations_url": "https://api.github.com/users/brentp/orgs",
            "repos_url": "https://api.github.com/users/brentp/repos",
            "events_url": "https://api.github.com/users/brentp/events{/privacy}",
            "received_events_url": "https://api.github.com/users/brentp/received_events",
            "type": "User",
            "site_admin": false
        },
        "created_at": "2017-02-08T02:52:08Z",
        "updated_at": "2017-02-08T02:52:08Z",
        "author_association": "CONTRIBUTOR",
        "body": "I made this PR because I couldn't build a (data) package before on my laptop with 8GB of memory. After this, I could build much larger recipes. \r\nGranted, it's a rare use-case since most software packages (and files) are tiny. So the severity is exactly dependent on the size of the package.\r\n\r\nI guess the solution would be to try mmap, catch the OSError and just read the file into memory. And then have a check to not call close() on the string."
    },
    {
        "url": "https://api.github.com/repos/conda/conda-build/issues/comments/206639621",
        "html_url": "https://github.com/conda/conda-build/issues/868#issuecomment-206639621",
        "issue_url": "https://api.github.com/repos/conda/conda-build/issues/868",
        "id": 206639621,
        "node_id": "MDEyOklzc3VlQ29tbWVudDIwNjYzOTYyMQ==",
        "user": {
            "login": "brentp",
            "id": 1739,
            "node_id": "MDQ6VXNlcjE3Mzk=",
            "avatar_url": "https://avatars2.githubusercontent.com/u/1739?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/brentp",
            "html_url": "https://github.com/brentp",
            "followers_url": "https://api.github.com/users/brentp/followers",
            "following_url": "https://api.github.com/users/brentp/following{/other_user}",
            "gists_url": "https://api.github.com/users/brentp/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/brentp/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/brentp/subscriptions",
            "organizations_url": "https://api.github.com/users/brentp/orgs",
            "repos_url": "https://api.github.com/users/brentp/repos",
            "events_url": "https://api.github.com/users/brentp/events{/privacy}",
            "received_events_url": "https://api.github.com/users/brentp/received_events",
            "type": "User",
            "site_admin": false
        },
        "created_at": "2016-04-07T00:59:26Z",
        "updated_at": "2016-04-07T00:59:26Z",
        "author_association": "CONTRIBUTOR",
        "body": "should be an easy fix. I'll have a PR tomorrow.\n"
    },
    {
        "url": "https://api.github.com/repos/conda/conda-build/issues/comments/206655935",
        "html_url": "https://github.com/conda/conda-build/issues/868#issuecomment-206655935",
        "issue_url": "https://api.github.com/repos/conda/conda-build/issues/868",
        "id": 206655935,
        "node_id": "MDEyOklzc3VlQ29tbWVudDIwNjY1NTkzNQ==",
        "user": {
            "login": "brentp",
            "id": 1739,
            "node_id": "MDQ6VXNlcjE3Mzk=",
            "avatar_url": "https://avatars2.githubusercontent.com/u/1739?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/brentp",
            "html_url": "https://github.com/brentp",
            "followers_url": "https://api.github.com/users/brentp/followers",
            "following_url": "https://api.github.com/users/brentp/following{/other_user}",
            "gists_url": "https://api.github.com/users/brentp/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/brentp/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/brentp/subscriptions",
            "organizations_url": "https://api.github.com/users/brentp/orgs",
            "repos_url": "https://api.github.com/users/brentp/repos",
            "events_url": "https://api.github.com/users/brentp/events{/privacy}",
            "received_events_url": "https://api.github.com/users/brentp/received_events",
            "type": "User",
            "site_admin": false
        },
        "created_at": "2016-04-07T01:53:53Z",
        "updated_at": "2016-04-07T01:53:53Z",
        "author_association": "CONTRIBUTOR",
        "body": "let me know any feedback on the pr in #869\n"
    },
    {
        "url": "https://api.github.com/repos/conda/conda-build/issues/comments/207139686",
        "html_url": "https://github.com/conda/conda-build/pull/870#issuecomment-207139686",
        "issue_url": "https://api.github.com/repos/conda/conda-build/issues/870",
        "id": 207139686,
        "node_id": "MDEyOklzc3VlQ29tbWVudDIwNzEzOTY4Ng==",
        "user": {
            "login": "brentp",
            "id": 1739,
            "node_id": "MDQ6VXNlcjE3Mzk=",
            "avatar_url": "https://avatars2.githubusercontent.com/u/1739?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/brentp",
            "html_url": "https://github.com/brentp",
            "followers_url": "https://api.github.com/users/brentp/followers",
            "following_url": "https://api.github.com/users/brentp/following{/other_user}",
            "gists_url": "https://api.github.com/users/brentp/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/brentp/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/brentp/subscriptions",
            "organizations_url": "https://api.github.com/users/brentp/orgs",
            "repos_url": "https://api.github.com/users/brentp/repos",
            "events_url": "https://api.github.com/users/brentp/events{/privacy}",
            "received_events_url": "https://api.github.com/users/brentp/received_events",
            "type": "User",
            "site_admin": false
        },
        "created_at": "2016-04-07T23:46:45Z",
        "updated_at": "2016-04-07T23:46:45Z",
        "author_association": "CONTRIBUTOR",
        "body": "this is the related change in binstar_client that takes advantage of the change here: https://github.com/Anaconda-Server/anaconda-client/pull/311\n"
    },
    {
        "url": "https://api.github.com/repos/conda/conda-build/issues/comments/207155408",
        "html_url": "https://github.com/conda/conda-build/pull/870#issuecomment-207155408",
        "issue_url": "https://api.github.com/repos/conda/conda-build/issues/870",
        "id": 207155408,
        "node_id": "MDEyOklzc3VlQ29tbWVudDIwNzE1NTQwOA==",
        "user": {
            "login": "brentp",
            "id": 1739,
            "node_id": "MDQ6VXNlcjE3Mzk=",
            "avatar_url": "https://avatars2.githubusercontent.com/u/1739?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/brentp",
            "html_url": "https://github.com/brentp",
            "followers_url": "https://api.github.com/users/brentp/followers",
            "following_url": "https://api.github.com/users/brentp/following{/other_user}",
            "gists_url": "https://api.github.com/users/brentp/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/brentp/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/brentp/subscriptions",
            "organizations_url": "https://api.github.com/users/brentp/orgs",
            "repos_url": "https://api.github.com/users/brentp/repos",
            "events_url": "https://api.github.com/users/brentp/events{/privacy}",
            "received_events_url": "https://api.github.com/users/brentp/received_events",
            "type": "User",
            "site_admin": false
        },
        "created_at": "2016-04-08T01:00:49Z",
        "updated_at": "2016-04-08T01:00:49Z",
        "author_association": "CONTRIBUTOR",
        "body": "I see a huge difference on e.g. https://anaconda.org/bspuu/reference/files with both changes. I will update the PR sort info/ to be first (and then by size) tomorrow morn.\n"
    },
    {
        "url": "https://api.github.com/repos/conda/conda-build/issues/comments/207397216",
        "html_url": "https://github.com/conda/conda-build/pull/870#issuecomment-207397216",
        "issue_url": "https://api.github.com/repos/conda/conda-build/issues/870",
        "id": 207397216,
        "node_id": "MDEyOklzc3VlQ29tbWVudDIwNzM5NzIxNg==",
        "user": {
            "login": "brentp",
            "id": 1739,
            "node_id": "MDQ6VXNlcjE3Mzk=",
            "avatar_url": "https://avatars2.githubusercontent.com/u/1739?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/brentp",
            "html_url": "https://github.com/brentp",
            "followers_url": "https://api.github.com/users/brentp/followers",
            "following_url": "https://api.github.com/users/brentp/following{/other_user}",
            "gists_url": "https://api.github.com/users/brentp/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/brentp/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/brentp/subscriptions",
            "organizations_url": "https://api.github.com/users/brentp/orgs",
            "repos_url": "https://api.github.com/users/brentp/repos",
            "events_url": "https://api.github.com/users/brentp/events{/privacy}",
            "received_events_url": "https://api.github.com/users/brentp/received_events",
            "type": "User",
            "site_admin": false
        },
        "created_at": "2016-04-08T11:48:34Z",
        "updated_at": "2016-04-08T11:48:34Z",
        "author_association": "CONTRIBUTOR",
        "body": "this should be good to go.\n"
    },
    {
        "url": "https://api.github.com/repos/conda/conda-build/issues/comments/208451828",
        "html_url": "https://github.com/conda/conda-build/pull/877#issuecomment-208451828",
        "issue_url": "https://api.github.com/repos/conda/conda-build/issues/877",
        "id": 208451828,
        "node_id": "MDEyOklzc3VlQ29tbWVudDIwODQ1MTgyOA==",
        "user": {
            "login": "brentp",
            "id": 1739,
            "node_id": "MDQ6VXNlcjE3Mzk=",
            "avatar_url": "https://avatars2.githubusercontent.com/u/1739?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/brentp",
            "html_url": "https://github.com/brentp",
            "followers_url": "https://api.github.com/users/brentp/followers",
            "following_url": "https://api.github.com/users/brentp/following{/other_user}",
            "gists_url": "https://api.github.com/users/brentp/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/brentp/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/brentp/subscriptions",
            "organizations_url": "https://api.github.com/users/brentp/orgs",
            "repos_url": "https://api.github.com/users/brentp/repos",
            "events_url": "https://api.github.com/users/brentp/events{/privacy}",
            "received_events_url": "https://api.github.com/users/brentp/received_events",
            "type": "User",
            "site_admin": false
        },
        "created_at": "2016-04-11T17:07:14Z",
        "updated_at": "2016-04-11T17:07:14Z",
        "author_association": "CONTRIBUTOR",
        "body": "Yes, please make much longer than 128.\n"
    },
    {
        "url": "https://api.github.com/repos/conda/conda-build/issues/comments/213596067",
        "html_url": "https://github.com/conda/conda-build/issues/889#issuecomment-213596067",
        "issue_url": "https://api.github.com/repos/conda/conda-build/issues/889",
        "id": 213596067,
        "node_id": "MDEyOklzc3VlQ29tbWVudDIxMzU5NjA2Nw==",
        "user": {
            "login": "brentp",
            "id": 1739,
            "node_id": "MDQ6VXNlcjE3Mzk=",
            "avatar_url": "https://avatars2.githubusercontent.com/u/1739?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/brentp",
            "html_url": "https://github.com/brentp",
            "followers_url": "https://api.github.com/users/brentp/followers",
            "following_url": "https://api.github.com/users/brentp/following{/other_user}",
            "gists_url": "https://api.github.com/users/brentp/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/brentp/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/brentp/subscriptions",
            "organizations_url": "https://api.github.com/users/brentp/orgs",
            "repos_url": "https://api.github.com/users/brentp/repos",
            "events_url": "https://api.github.com/users/brentp/events{/privacy}",
            "received_events_url": "https://api.github.com/users/brentp/received_events",
            "type": "User",
            "site_admin": false
        },
        "created_at": "2016-04-22T21:37:59Z",
        "updated_at": "2016-04-22T21:37:59Z",
        "author_association": "CONTRIBUTOR",
        "body": "yes, that's me. looks like we can just add .decode('ascii')  to the write. trying to figure out how to trigger this error in the existing tests...\n"
    },
    {
        "url": "https://api.github.com/repos/conda/conda-build/issues/comments/213601443",
        "html_url": "https://github.com/conda/conda-build/issues/889#issuecomment-213601443",
        "issue_url": "https://api.github.com/repos/conda/conda-build/issues/889",
        "id": 213601443,
        "node_id": "MDEyOklzc3VlQ29tbWVudDIxMzYwMTQ0Mw==",
        "user": {
            "login": "brentp",
            "id": 1739,
            "node_id": "MDQ6VXNlcjE3Mzk=",
            "avatar_url": "https://avatars2.githubusercontent.com/u/1739?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/brentp",
            "html_url": "https://github.com/brentp",
            "followers_url": "https://api.github.com/users/brentp/followers",
            "following_url": "https://api.github.com/users/brentp/following{/other_user}",
            "gists_url": "https://api.github.com/users/brentp/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/brentp/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/brentp/subscriptions",
            "organizations_url": "https://api.github.com/users/brentp/orgs",
            "repos_url": "https://api.github.com/users/brentp/repos",
            "events_url": "https://api.github.com/users/brentp/events{/privacy}",
            "received_events_url": "https://api.github.com/users/brentp/received_events",
            "type": "User",
            "site_admin": false
        },
        "created_at": "2016-04-22T21:54:58Z",
        "updated_at": "2016-04-22T21:54:58Z",
        "author_association": "CONTRIBUTOR",
        "body": "I thinks it's with detect_binary_files_with_prefix: true\n"
    },
    {
        "url": "https://api.github.com/repos/conda/conda-build/issues/comments/213602183",
        "html_url": "https://github.com/conda/conda-build/issues/889#issuecomment-213602183",
        "issue_url": "https://api.github.com/repos/conda/conda-build/issues/889",
        "id": 213602183,
        "node_id": "MDEyOklzc3VlQ29tbWVudDIxMzYwMjE4Mw==",
        "user": {
            "login": "brentp",
            "id": 1739,
            "node_id": "MDQ6VXNlcjE3Mzk=",
            "avatar_url": "https://avatars2.githubusercontent.com/u/1739?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/brentp",
            "html_url": "https://github.com/brentp",
            "followers_url": "https://api.github.com/users/brentp/followers",
            "following_url": "https://api.github.com/users/brentp/following{/other_user}",
            "gists_url": "https://api.github.com/users/brentp/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/brentp/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/brentp/subscriptions",
            "organizations_url": "https://api.github.com/users/brentp/orgs",
            "repos_url": "https://api.github.com/users/brentp/repos",
            "events_url": "https://api.github.com/users/brentp/events{/privacy}",
            "received_events_url": "https://api.github.com/users/brentp/received_events",
            "type": "User",
            "site_admin": false
        },
        "created_at": "2016-04-22T21:56:11Z",
        "updated_at": "2016-04-22T21:56:11Z",
        "author_association": "CONTRIBUTOR",
        "body": "aye. but reading that is where I got the idea... :|\n"
    },
    {
        "url": "https://api.github.com/repos/conda/conda-build/issues/comments/213606449",
        "html_url": "https://github.com/conda/conda-build/pull/892#issuecomment-213606449",
        "issue_url": "https://api.github.com/repos/conda/conda-build/issues/892",
        "id": 213606449,
        "node_id": "MDEyOklzc3VlQ29tbWVudDIxMzYwNjQ0OQ==",
        "user": {
            "login": "brentp",
            "id": 1739,
            "node_id": "MDQ6VXNlcjE3Mzk=",
            "avatar_url": "https://avatars2.githubusercontent.com/u/1739?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/brentp",
            "html_url": "https://github.com/brentp",
            "followers_url": "https://api.github.com/users/brentp/followers",
            "following_url": "https://api.github.com/users/brentp/following{/other_user}",
            "gists_url": "https://api.github.com/users/brentp/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/brentp/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/brentp/subscriptions",
            "organizations_url": "https://api.github.com/users/brentp/orgs",
            "repos_url": "https://api.github.com/users/brentp/repos",
            "events_url": "https://api.github.com/users/brentp/events{/privacy}",
            "received_events_url": "https://api.github.com/users/brentp/received_events",
            "type": "User",
            "site_admin": false
        },
        "created_at": "2016-04-22T22:11:25Z",
        "updated_at": "2016-04-22T22:11:25Z",
        "author_association": "CONTRIBUTOR",
        "body": "I tried to get the tests to fail in #893, but no luck. This should fix #889, but any insight on making a test break would be great.\n"
    },
    {
        "url": "https://api.github.com/repos/conda/conda-build/issues/comments/214757274",
        "html_url": "https://github.com/conda/conda-build/issues/899#issuecomment-214757274",
        "issue_url": "https://api.github.com/repos/conda/conda-build/issues/899",
        "id": 214757274,
        "node_id": "MDEyOklzc3VlQ29tbWVudDIxNDc1NzI3NA==",
        "user": {
            "login": "brentp",
            "id": 1739,
            "node_id": "MDQ6VXNlcjE3Mzk=",
            "avatar_url": "https://avatars2.githubusercontent.com/u/1739?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/brentp",
            "html_url": "https://github.com/brentp",
            "followers_url": "https://api.github.com/users/brentp/followers",
            "following_url": "https://api.github.com/users/brentp/following{/other_user}",
            "gists_url": "https://api.github.com/users/brentp/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/brentp/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/brentp/subscriptions",
            "organizations_url": "https://api.github.com/users/brentp/orgs",
            "repos_url": "https://api.github.com/users/brentp/repos",
            "events_url": "https://api.github.com/users/brentp/events{/privacy}",
            "received_events_url": "https://api.github.com/users/brentp/received_events",
            "type": "User",
            "site_admin": false
        },
        "created_at": "2016-04-26T14:08:42Z",
        "updated_at": "2016-04-26T14:19:38Z",
        "author_association": "CONTRIBUTOR",
        "body": "I'm probably misusing conda. I'm trying to specify a dependency for the pre-link.sh script. It seems like a PATH is not set correctly. Here's a meta.yaml (where samtools is in bioconda channel):\n\n```\n# fake/meta.yaml\npackage:\n  name: fake\n  version: '123'\n\nrequirements:\n  build:\n  - samtools\n  run:\n  - samtools\n```\n\nand a pre-link.sh\n\n```\n# fake/pre-link.sh\nsamtools --help\n```\n\nwhen I run `conda build ./fake` there are no problems and it installs `samtools` and the dependencies into $CONDA_ROOT/envs/_build/bin/samtools\nIt builds the .bz2, when I run: \n\n```\nconda install $CONDA_ROOT/conda-bld/linux-64/fake-123-0.tar.bz2\n```\n\nthen it shows:\n\n```\n/pkgs/fake-123-0/bin/.fake-pre-link.sh: line 1: samtools: command not found\nError: pre-link failed: fake-123-0\n```\n"
    },
    {
        "url": "https://api.github.com/repos/conda/conda-build/issues/comments/214767717",
        "html_url": "https://github.com/conda/conda-build/issues/899#issuecomment-214767717",
        "issue_url": "https://api.github.com/repos/conda/conda-build/issues/899",
        "id": 214767717,
        "node_id": "MDEyOklzc3VlQ29tbWVudDIxNDc2NzcxNw==",
        "user": {
            "login": "brentp",
            "id": 1739,
            "node_id": "MDQ6VXNlcjE3Mzk=",
            "avatar_url": "https://avatars2.githubusercontent.com/u/1739?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/brentp",
            "html_url": "https://github.com/brentp",
            "followers_url": "https://api.github.com/users/brentp/followers",
            "following_url": "https://api.github.com/users/brentp/following{/other_user}",
            "gists_url": "https://api.github.com/users/brentp/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/brentp/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/brentp/subscriptions",
            "organizations_url": "https://api.github.com/users/brentp/orgs",
            "repos_url": "https://api.github.com/users/brentp/repos",
            "events_url": "https://api.github.com/users/brentp/events{/privacy}",
            "received_events_url": "https://api.github.com/users/brentp/received_events",
            "type": "User",
            "site_admin": false
        },
        "created_at": "2016-04-26T14:41:25Z",
        "updated_at": "2016-04-26T14:41:25Z",
        "author_association": "CONTRIBUTOR",
        "body": "ok. thanks. with conda@master, I get:\n\n```\nanaconda/lib/python2.7/site-packages/conda/install.py\", line 717, in extract\n    rec = package_cache()[dist]\nKeyError: 'fake-123-0'\n```\n\nThe actual key seems to be `<unknown>::fake-123-0`\n"
    },
    {
        "url": "https://api.github.com/repos/conda/conda-build/issues/comments/214819476",
        "html_url": "https://github.com/conda/conda-build/issues/899#issuecomment-214819476",
        "issue_url": "https://api.github.com/repos/conda/conda-build/issues/899",
        "id": 214819476,
        "node_id": "MDEyOklzc3VlQ29tbWVudDIxNDgxOTQ3Ng==",
        "user": {
            "login": "brentp",
            "id": 1739,
            "node_id": "MDQ6VXNlcjE3Mzk=",
            "avatar_url": "https://avatars2.githubusercontent.com/u/1739?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/brentp",
            "html_url": "https://github.com/brentp",
            "followers_url": "https://api.github.com/users/brentp/followers",
            "following_url": "https://api.github.com/users/brentp/following{/other_user}",
            "gists_url": "https://api.github.com/users/brentp/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/brentp/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/brentp/subscriptions",
            "organizations_url": "https://api.github.com/users/brentp/orgs",
            "repos_url": "https://api.github.com/users/brentp/repos",
            "events_url": "https://api.github.com/users/brentp/events{/privacy}",
            "received_events_url": "https://api.github.com/users/brentp/received_events",
            "type": "User",
            "site_admin": false
        },
        "created_at": "2016-04-26T17:27:52Z",
        "updated_at": "2016-04-26T17:27:52Z",
        "author_association": "CONTRIBUTOR",
        "body": "I think this might be related to: https://github.com/conda/conda/issues/2358 and https://github.com/conda/conda/pull/2369\n"
    },
    {
        "url": "https://api.github.com/repos/conda/conda-build/issues/comments/215860333",
        "html_url": "https://github.com/conda/conda-build/issues/899#issuecomment-215860333",
        "issue_url": "https://api.github.com/repos/conda/conda-build/issues/899",
        "id": 215860333,
        "node_id": "MDEyOklzc3VlQ29tbWVudDIxNTg2MDMzMw==",
        "user": {
            "login": "brentp",
            "id": 1739,
            "node_id": "MDQ6VXNlcjE3Mzk=",
            "avatar_url": "https://avatars2.githubusercontent.com/u/1739?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/brentp",
            "html_url": "https://github.com/brentp",
            "followers_url": "https://api.github.com/users/brentp/followers",
            "following_url": "https://api.github.com/users/brentp/following{/other_user}",
            "gists_url": "https://api.github.com/users/brentp/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/brentp/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/brentp/subscriptions",
            "organizations_url": "https://api.github.com/users/brentp/orgs",
            "repos_url": "https://api.github.com/users/brentp/repos",
            "events_url": "https://api.github.com/users/brentp/events{/privacy}",
            "received_events_url": "https://api.github.com/users/brentp/received_events",
            "type": "User",
            "site_admin": false
        },
        "created_at": "2016-04-29T19:48:21Z",
        "updated_at": "2016-04-29T19:48:21Z",
        "author_association": "CONTRIBUTOR",
        "body": "I am able to get conda master to work with these changes. Is there a better way to address this upstream?\n\n``` patch\n$ git diff\ndiff --git a/conda/install.py b/conda/install.py\nindex 86a6c7b..98785d8 100644\n--- a/conda/install.py\n+++ b/conda/install.py\n@@ -693,6 +693,9 @@ def is_extracted(dist):\n     for fn in package_cache().get(dist, {}).get('dirs', ()):\n         return fn\n\n+    if not dist.startswith(\"<unknown>::\"):\n+        return is_extracted(\"<unknown>::\" + dist)\n+\n def rm_extracted(dist):\n     \"\"\"\n     Removes any extracted versions of the given package found in the cache.\n@@ -713,7 +716,11 @@ def extract(dist):\n     Extract a package, i.e. make a package available for linkage. We assume\n     that the compressed package is located in the packages directory.\n     \"\"\"\n-    rec = package_cache()[dist]\n+    try:\n+        rec = package_cache()[dist]\n+    except KeyError:\n+        rec = package_cache()[\"<unknown>::\" + dist]\n+\n     url = rec['urls'][0]\n     fname = rec['files'][0]\n     assert url and fname\n```\n\nI see lots of \"unknown\" packages in my package cache, e.g.\n\n```\n'<unknown>::conda-3.19.0-py27_0', '<unknown>::conda-env-2.4.5-py27_0', '<unknown>::fake-123-0', '<unknown>::openssl-1.0.2d-0', '<unknown>::pip-7.1.2-py27_0', '<unknown>::pycosat-0.6.1-py27_0', '<unknown>::pycrypto-2.6.1-py27_0', '<unknown>::python-2.7.11-0', '<unknown>::pyyaml-3.11-py27_1', '<unknown>::readline-6.2-2', '<unknown>::requests-2.9.0-py27_0', '<unknown>::setuptools-18.8.1-py27_0', '<unknown>::sqlite-3.8.4.1-1', '<unknown>::tk-8.5.18-0', '<unknown>::wheel-0.26.0-py27_1', '<unknown>::yaml-0.1.6-0'\n```\n"
    },
    {
        "url": "https://api.github.com/repos/conda/conda-build/issues/comments/215882463",
        "html_url": "https://github.com/conda/conda-build/issues/899#issuecomment-215882463",
        "issue_url": "https://api.github.com/repos/conda/conda-build/issues/899",
        "id": 215882463,
        "node_id": "MDEyOklzc3VlQ29tbWVudDIxNTg4MjQ2Mw==",
        "user": {
            "login": "brentp",
            "id": 1739,
            "node_id": "MDQ6VXNlcjE3Mzk=",
            "avatar_url": "https://avatars2.githubusercontent.com/u/1739?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/brentp",
            "html_url": "https://github.com/brentp",
            "followers_url": "https://api.github.com/users/brentp/followers",
            "following_url": "https://api.github.com/users/brentp/following{/other_user}",
            "gists_url": "https://api.github.com/users/brentp/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/brentp/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/brentp/subscriptions",
            "organizations_url": "https://api.github.com/users/brentp/orgs",
            "repos_url": "https://api.github.com/users/brentp/repos",
            "events_url": "https://api.github.com/users/brentp/events{/privacy}",
            "received_events_url": "https://api.github.com/users/brentp/received_events",
            "type": "User",
            "site_admin": false
        },
        "created_at": "2016-04-29T21:09:14Z",
        "updated_at": "2016-04-29T21:09:14Z",
        "author_association": "CONTRIBUTOR",
        "body": "not sure if this helps, but those are likely the ones I installed with `python setup.py install` or `pip`.\n"
    },
    {
        "url": "https://api.github.com/repos/conda/conda-build/issues/comments/216634605",
        "html_url": "https://github.com/conda/conda-build/issues/899#issuecomment-216634605",
        "issue_url": "https://api.github.com/repos/conda/conda-build/issues/899",
        "id": 216634605,
        "node_id": "MDEyOklzc3VlQ29tbWVudDIxNjYzNDYwNQ==",
        "user": {
            "login": "brentp",
            "id": 1739,
            "node_id": "MDQ6VXNlcjE3Mzk=",
            "avatar_url": "https://avatars2.githubusercontent.com/u/1739?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/brentp",
            "html_url": "https://github.com/brentp",
            "followers_url": "https://api.github.com/users/brentp/followers",
            "following_url": "https://api.github.com/users/brentp/following{/other_user}",
            "gists_url": "https://api.github.com/users/brentp/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/brentp/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/brentp/subscriptions",
            "organizations_url": "https://api.github.com/users/brentp/orgs",
            "repos_url": "https://api.github.com/users/brentp/repos",
            "events_url": "https://api.github.com/users/brentp/events{/privacy}",
            "received_events_url": "https://api.github.com/users/brentp/received_events",
            "type": "User",
            "site_admin": false
        },
        "created_at": "2016-05-03T19:12:06Z",
        "updated_at": "2016-05-03T19:12:06Z",
        "author_association": "CONTRIBUTOR",
        "body": "cheers.\n"
    },
    {
        "url": "https://api.github.com/repos/conda/conda-build/issues/comments/218197223",
        "html_url": "https://github.com/conda/conda-build/issues/899#issuecomment-218197223",
        "issue_url": "https://api.github.com/repos/conda/conda-build/issues/899",
        "id": 218197223,
        "node_id": "MDEyOklzc3VlQ29tbWVudDIxODE5NzIyMw==",
        "user": {
            "login": "brentp",
            "id": 1739,
            "node_id": "MDQ6VXNlcjE3Mzk=",
            "avatar_url": "https://avatars2.githubusercontent.com/u/1739?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/brentp",
            "html_url": "https://github.com/brentp",
            "followers_url": "https://api.github.com/users/brentp/followers",
            "following_url": "https://api.github.com/users/brentp/following{/other_user}",
            "gists_url": "https://api.github.com/users/brentp/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/brentp/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/brentp/subscriptions",
            "organizations_url": "https://api.github.com/users/brentp/orgs",
            "repos_url": "https://api.github.com/users/brentp/repos",
            "events_url": "https://api.github.com/users/brentp/events{/privacy}",
            "received_events_url": "https://api.github.com/users/brentp/received_events",
            "type": "User",
            "site_admin": false
        },
        "created_at": "2016-05-10T15:38:23Z",
        "updated_at": "2016-05-10T15:38:23Z",
        "author_association": "CONTRIBUTOR",
        "body": "actually, with the example above, I still get:\n\n```\nTraceback (most recent call last):\n  File \"/data/miniconda2/bin/conda\", line 9, in <module>\n    load_entry_point('conda==3.19.1.dev654+g91847aa', 'console_scripts', 'conda')()\n  File \"/data/miniconda2/lib/python2.7/site-packages/conda-3.19.1.dev654+g91847aa-py2.7.egg/conda/cli/main.py\", line 120, in main\n    args_func(args, p)\n  File \"/data/miniconda2/lib/python2.7/site-packages/conda-3.19.1.dev654+g91847aa-py2.7.egg/conda/cli/main.py\", line 127, in args_func\n    args.func(args, p)\n  File \"/data/miniconda2/lib/python2.7/site-packages/conda-3.19.1.dev654+g91847aa-py2.7.egg/conda/cli/main_install.py\", line 62, in execute\n    install.install(args, parser, 'install')\n  File \"/data/miniconda2/lib/python2.7/site-packages/conda-3.19.1.dev654+g91847aa-py2.7.egg/conda/cli/install.py\", line 193, in install\n    misc.explicit(args.packages, prefix, verbose=not args.quiet)\n  File \"/data/miniconda2/lib/python2.7/site-packages/conda-3.19.1.dev654+g91847aa-py2.7.egg/conda/misc.py\", line 123, in explicit\n    execute_actions(actions, index=index, verbose=verbose)\n  File \"/data/miniconda2/lib/python2.7/site-packages/conda-3.19.1.dev654+g91847aa-py2.7.egg/conda/plan.py\", line 554, in execute_actions\n    inst.execute_instructions(plan, index, verbose)\n  File \"/data/miniconda2/lib/python2.7/site-packages/conda-3.19.1.dev654+g91847aa-py2.7.egg/conda/instructions.py\", line 137, in execute_instructions\n    cmd(state, arg)\n  File \"/data/miniconda2/lib/python2.7/site-packages/conda-3.19.1.dev654+g91847aa-py2.7.egg/conda/instructions.py\", line 47, in FETCH_CMD\n    fetch_pkg(state['index'][arg + '.tar.bz2'])\nKeyError: 'local::fake-123-0.tar.bz2'\n```\n\nthe commands to reproduce are just:\n\n```\nconda build ./fake\nconda install $(conda info --root)/conda-bld/linux-64/fake-123-0.tar.bz2\n```\n\nfor me `state['index']` is empty at that point.\n"
    },
    {
        "url": "https://api.github.com/repos/conda/conda-build/issues/comments/218231242",
        "html_url": "https://github.com/conda/conda-build/issues/899#issuecomment-218231242",
        "issue_url": "https://api.github.com/repos/conda/conda-build/issues/899",
        "id": 218231242,
        "node_id": "MDEyOklzc3VlQ29tbWVudDIxODIzMTI0Mg==",
        "user": {
            "login": "brentp",
            "id": 1739,
            "node_id": "MDQ6VXNlcjE3Mzk=",
            "avatar_url": "https://avatars2.githubusercontent.com/u/1739?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/brentp",
            "html_url": "https://github.com/brentp",
            "followers_url": "https://api.github.com/users/brentp/followers",
            "following_url": "https://api.github.com/users/brentp/following{/other_user}",
            "gists_url": "https://api.github.com/users/brentp/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/brentp/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/brentp/subscriptions",
            "organizations_url": "https://api.github.com/users/brentp/orgs",
            "repos_url": "https://api.github.com/users/brentp/repos",
            "events_url": "https://api.github.com/users/brentp/events{/privacy}",
            "received_events_url": "https://api.github.com/users/brentp/received_events",
            "type": "User",
            "site_admin": false
        },
        "created_at": "2016-05-10T17:30:58Z",
        "updated_at": "2016-05-10T17:30:58Z",
        "author_association": "CONTRIBUTOR",
        "body": "here is a standalone bash script to recreate:\n\n```\nset -eo pipefail\n\nrm -rf fake && mkdir -p fake\necho \"\npackage:\n  name: fake\n  version: '123'\n\n\" > fake/meta.yaml\n\necho \"ls -lh\" > fake/pre-link.sh\n\nconda build fake\nconda install $(conda info --root)/conda-bld/*/fake-123-0.tar.bz2\n```\n"
    }
]