[
    {
        "url": "https://api.github.com/repos/Deeplodocus/deeplodocus/issues/246",
        "repository_url": "https://api.github.com/repos/Deeplodocus/deeplodocus",
        "labels_url": "https://api.github.com/repos/Deeplodocus/deeplodocus/issues/246/labels{/name}",
        "comments_url": "https://api.github.com/repos/Deeplodocus/deeplodocus/issues/246/comments",
        "events_url": "https://api.github.com/repos/Deeplodocus/deeplodocus/issues/246/events",
        "html_url": "https://github.com/Deeplodocus/deeplodocus/issues/246",
        "id": 482717567,
        "node_id": "MDU6SXNzdWU0ODI3MTc1Njc=",
        "number": 246,
        "title": "Unable to specify special data types in config files",
        "user": {
            "login": "samuelwestlake",
            "id": 17575849,
            "node_id": "MDQ6VXNlcjE3NTc1ODQ5",
            "avatar_url": "https://avatars1.githubusercontent.com/u/17575849?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/samuelwestlake",
            "html_url": "https://github.com/samuelwestlake",
            "followers_url": "https://api.github.com/users/samuelwestlake/followers",
            "following_url": "https://api.github.com/users/samuelwestlake/following{/other_user}",
            "gists_url": "https://api.github.com/users/samuelwestlake/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/samuelwestlake/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/samuelwestlake/subscriptions",
            "organizations_url": "https://api.github.com/users/samuelwestlake/orgs",
            "repos_url": "https://api.github.com/users/samuelwestlake/repos",
            "events_url": "https://api.github.com/users/samuelwestlake/events{/privacy}",
            "received_events_url": "https://api.github.com/users/samuelwestlake/received_events",
            "type": "User",
            "site_admin": false
        },
        "labels": [],
        "state": "open",
        "locked": false,
        "assignee": null,
        "assignees": [],
        "milestone": null,
        "comments": 0,
        "created_at": "2019-08-20T08:28:06Z",
        "updated_at": "2019-08-20T08:28:06Z",
        "closed_at": null,
        "author_association": "CONTRIBUTOR",
        "body": "For example, the 'weight' argument for PyTorch's CrossEntropyLoss should be a torch tensors, but this can not currently be specified directly as a kwarg on config.  "
    },
    {
        "url": "https://api.github.com/repos/Deeplodocus/deeplodocus/issues/239",
        "repository_url": "https://api.github.com/repos/Deeplodocus/deeplodocus",
        "labels_url": "https://api.github.com/repos/Deeplodocus/deeplodocus/issues/239/labels{/name}",
        "comments_url": "https://api.github.com/repos/Deeplodocus/deeplodocus/issues/239/comments",
        "events_url": "https://api.github.com/repos/Deeplodocus/deeplodocus/issues/239/events",
        "html_url": "https://github.com/Deeplodocus/deeplodocus/issues/239",
        "id": 476457434,
        "node_id": "MDU6SXNzdWU0NzY0NTc0MzQ=",
        "number": 239,
        "title": "Ambiguous Deep Fatal Error",
        "user": {
            "login": "samuelwestlake",
            "id": 17575849,
            "node_id": "MDQ6VXNlcjE3NTc1ODQ5",
            "avatar_url": "https://avatars1.githubusercontent.com/u/17575849?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/samuelwestlake",
            "html_url": "https://github.com/samuelwestlake",
            "followers_url": "https://api.github.com/users/samuelwestlake/followers",
            "following_url": "https://api.github.com/users/samuelwestlake/following{/other_user}",
            "gists_url": "https://api.github.com/users/samuelwestlake/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/samuelwestlake/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/samuelwestlake/subscriptions",
            "organizations_url": "https://api.github.com/users/samuelwestlake/orgs",
            "repos_url": "https://api.github.com/users/samuelwestlake/repos",
            "events_url": "https://api.github.com/users/samuelwestlake/events{/privacy}",
            "received_events_url": "https://api.github.com/users/samuelwestlake/received_events",
            "type": "User",
            "site_admin": false
        },
        "labels": [],
        "state": "open",
        "locked": false,
        "assignee": null,
        "assignees": [],
        "milestone": null,
        "comments": 1,
        "created_at": "2019-08-03T14:37:17Z",
        "updated_at": "2019-09-06T19:12:45Z",
        "closed_at": null,
        "author_association": "CONTRIBUTOR",
        "body": "When given an incorrect file/directory path as a data source, the resultant error says: 'Loading from premade dataset not implemented yet'. \r\n\r\nThis seems to be because the code assumes that if the path doesn't exist, we must be trying to load a pre-made dataset, but this isn't always the case. "
    }
]