[
    {
        "url": "https://api.github.com/repos/protolambda/zrnt/issues/19",
        "repository_url": "https://api.github.com/repos/protolambda/zrnt",
        "labels_url": "https://api.github.com/repos/protolambda/zrnt/issues/19/labels{/name}",
        "comments_url": "https://api.github.com/repos/protolambda/zrnt/issues/19/comments",
        "events_url": "https://api.github.com/repos/protolambda/zrnt/issues/19/events",
        "html_url": "https://github.com/protolambda/zrnt/pull/19",
        "id": 532319354,
        "node_id": "MDExOlB1bGxSZXF1ZXN0MzQ4NTkzNTMw",
        "number": 19,
        "title": "Update `GetBeaconCommittee` error messages for 0.9.x\"",
        "user": {
            "login": "gnattishness",
            "id": 1620192,
            "node_id": "MDQ6VXNlcjE2MjAxOTI=",
            "avatar_url": "https://avatars2.githubusercontent.com/u/1620192?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/gnattishness",
            "html_url": "https://github.com/gnattishness",
            "followers_url": "https://api.github.com/users/gnattishness/followers",
            "following_url": "https://api.github.com/users/gnattishness/following{/other_user}",
            "gists_url": "https://api.github.com/users/gnattishness/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/gnattishness/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/gnattishness/subscriptions",
            "organizations_url": "https://api.github.com/users/gnattishness/orgs",
            "repos_url": "https://api.github.com/users/gnattishness/repos",
            "events_url": "https://api.github.com/users/gnattishness/events{/privacy}",
            "received_events_url": "https://api.github.com/users/gnattishness/received_events",
            "type": "User",
            "site_admin": false
        },
        "labels": [],
        "state": "open",
        "locked": false,
        "assignee": null,
        "assignees": [],
        "milestone": null,
        "comments": 0,
        "created_at": "2019-12-03T22:49:31Z",
        "updated_at": "2019-12-03T22:49:54Z",
        "closed_at": null,
        "author_association": "NONE",
        "pull_request": {
            "url": "https://api.github.com/repos/protolambda/zrnt/pulls/19",
            "html_url": "https://github.com/protolambda/zrnt/pull/19",
            "diff_url": "https://github.com/protolambda/zrnt/pull/19.diff",
            "patch_url": "https://github.com/protolambda/zrnt/pull/19.patch"
        },
        "body": "Tiny fix."
    },
    {
        "url": "https://api.github.com/repos/protolambda/zrnt/issues/18",
        "repository_url": "https://api.github.com/repos/protolambda/zrnt",
        "labels_url": "https://api.github.com/repos/protolambda/zrnt/issues/18/labels{/name}",
        "comments_url": "https://api.github.com/repos/protolambda/zrnt/issues/18/comments",
        "events_url": "https://api.github.com/repos/protolambda/zrnt/issues/18/events",
        "html_url": "https://github.com/protolambda/zrnt/issues/18",
        "id": 530832750,
        "node_id": "MDU6SXNzdWU1MzA4MzI3NTA=",
        "number": 18,
        "title": "`computeProposerIndex` to return and propagate an error?",
        "user": {
            "login": "gnattishness",
            "id": 1620192,
            "node_id": "MDQ6VXNlcjE2MjAxOTI=",
            "avatar_url": "https://avatars2.githubusercontent.com/u/1620192?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/gnattishness",
            "html_url": "https://github.com/gnattishness",
            "followers_url": "https://api.github.com/users/gnattishness/followers",
            "following_url": "https://api.github.com/users/gnattishness/following{/other_user}",
            "gists_url": "https://api.github.com/users/gnattishness/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/gnattishness/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/gnattishness/subscriptions",
            "organizations_url": "https://api.github.com/users/gnattishness/orgs",
            "repos_url": "https://api.github.com/users/gnattishness/repos",
            "events_url": "https://api.github.com/users/gnattishness/events{/privacy}",
            "received_events_url": "https://api.github.com/users/gnattishness/received_events",
            "type": "User",
            "site_admin": false
        },
        "labels": [],
        "state": "open",
        "locked": false,
        "assignee": null,
        "assignees": [],
        "milestone": null,
        "comments": 1,
        "created_at": "2019-12-02T01:05:14Z",
        "updated_at": "2019-12-02T01:10:44Z",
        "closed_at": null,
        "author_association": "NONE",
        "body": "In spec v0.9.x, [`compute_proposer_index`](https://github.com/ethereum/eth2.0-specs/blob/v0.9.1/specs/core/0_beacon-chain.md#compute_proposer_index) asserts `indices > 0`, where previously this was unguarded and would result in a `ZeroDivisionError` (e.g. in [`get_beacon_proposer_index`](https://github.com/ethereum/eth2.0-specs/blob/v0.8.4/specs/core/0_beacon-chain.md#get_beacon_proposer_index)).\r\n\r\nNow that this is explicitly checked in the python spec, should ZRNT return and propagate an error in order to maintain equivalence?"
    }
]